#!/usr/bin/env python3
"""Generate symbols.hpp, symbols.cpp and .gitignore from symbols.rules."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve()
while not (_REPO_ROOT / "tools").is_dir():
    _REPO_ROOT = _REPO_ROOT.parent
sys.path.insert(0, str(_REPO_ROOT))

from tools.rules_kit import (
    RuleError,
    cpp_string,
    gitignore_lines,
    strip_comment,
    write_generated as write_generated_files,
)


@dataclass
class DataField:
    name: str
    cpp_type: str
    line_no: int


@dataclass
class SymbolsRules:
    kinds: list[str] = field(default_factory=list)
    data_fields: list[DataField] = field(default_factory=list)


def _short_cpp_type(cpp_type: str) -> str:
    return cpp_type.rsplit("::", 1)[-1]


def parse_rules(text: str, path: Path) -> SymbolsRules:
    section = ""
    kinds: list[str] = []
    data_fields: list[DataField] = []
    seen_kinds: set[str] = set()
    seen_fields: set[str] = set()

    for line_no, raw in enumerate(text.splitlines(), start=1):
        line = strip_comment(raw)
        if not line:
            continue

        header = re.fullmatch(r"\[([^\]]+)\]", line)
        if header:
            section = header.group(1).strip().lower()
            if section not in {"kinds", "data"}:
                raise RuleError(line_no, f"seccao desconhecida: [{section}]")
            continue

        if section == "kinds":
            name = line.strip()
            if not re.fullmatch(r"[A-Z][A-Za-z0-9_]*", name):
                raise RuleError(
                    line_no,
                    f"nome de kind invalido (deve começar com maiuscula): {name!r}",
                )
            if name in seen_kinds:
                raise RuleError(line_no, f"kind repetido: {name!r}")
            seen_kinds.add(name)
            kinds.append(name)
            continue

        if section == "data":
            if ":" not in line:
                raise RuleError(line_no, f"campo sem tipo: {line!r}")
            name, cpp_type = (part.strip() for part in line.split(":", 1))
            if not re.fullmatch(r"[a-z][A-Za-z0-9_]*", name):
                raise RuleError(
                    line_no,
                    f"nome de campo invalido (deve começar com minuscula): {name!r}",
                )
            if not cpp_type:
                raise RuleError(line_no, f"tipo vazio para campo: {name!r}")
            if name in seen_fields:
                raise RuleError(line_no, f"campo repetido: {name!r}")
            seen_fields.add(name)
            data_fields.append(DataField(name=name, cpp_type=cpp_type, line_no=line_no))
            continue

    if not kinds:
        raise RuleError(1, "[kinds] tem de declarar pelo menos um kind")
    if not data_fields:
        raise RuleError(1, "[data] tem de declarar pelo menos um campo")
    return SymbolsRules(kinds=kinds, data_fields=data_fields)


def _emit_header(rules: SymbolsRules) -> str:
    out: list[str] = []
    out.append("// auto-generated by src/symbols/generate.py — do not edit by hand")
    out.append("#pragma once")
    out.append("")
    out.append('#include "common/memory/arena.hpp"')
    out.append('#include "common/memory/dyn-array.hpp"')
    out.append('#include "common/memory/flat-map.hpp"')
    out.append('#include "common/memory/optional.hpp"')
    out.append('#include "common/memory/span.hpp"')
    out.append('#include "common/memory/string-interner.hpp"')
    out.append("")
    out.append("#include <cstdint>")
    out.append("#include <cstdio>")
    out.append("")
    out.append("namespace toolkit::symbols {")
    out.append("")
    out.append("using common::memory::InternedId;")
    out.append("using common::memory::Span;")
    out.append("using common::memory::DynArray;")
    out.append("using common::memory::Arena;")
    out.append("")
    out.append("using ModuleId = uint32_t;")
    out.append("static constexpr ModuleId kInvalidModule = ~0u;")
    out.append("")
    out.append("struct SymId {")
    out.append("    ModuleId module;")
    out.append("    uint32_t local;")
    out.append("")
    out.append("    constexpr SymId() = delete;")
    out.append("    constexpr SymId(ModuleId module_, uint32_t local_)")
    out.append("        : module(module_), local(local_) {}")
    out.append("")
    out.append("    bool operator==(const SymId &other) const noexcept {")
    out.append("        return module == other.module && local == other.local;")
    out.append("    }")
    out.append("    bool operator!=(const SymId &other) const noexcept {")
    out.append("        return !(*this == other);")
    out.append("    }")
    out.append("};")
    out.append("")
    out.append("static constexpr SymId kInvalidSymId{kInvalidModule, 0};")
    out.append("")
    out.append("using ScopeId = uint32_t;")
    out.append("static constexpr ScopeId kInvalidScopeId = ~0u;")
    out.append("")
    out.append("enum class SymKind : uint8_t {")
    for kind in rules.kinds:
        out.append(f"    {kind},")
    out.append("};")
    out.append("")
    out.append(f"static constexpr size_t kSymKindCount = {len(rules.kinds)};")

    out.append("")
    out.append("enum class SymbolVisibilityKind : uint8_t {")
    out.append("    Public,")
    out.append("    Private,")
    out.append("    Module,")
    out.append("};")
    out.append("")
    out.append("struct ModuleVisibilityRange {")
    out.append("    int32_t ancestors   = -1;")
    out.append("    int32_t descendants = -1;")
    out.append("};")
    out.append("")
    out.append("struct SymbolVisibility {")
    out.append("    SymbolVisibilityKind kind = SymbolVisibilityKind::Private;")
    out.append("    ModuleVisibilityRange range{};")
    out.append("};")
    out.append("")
    out.append("struct SymbolData {")
    scalar_types = {
        "InternedId",
        "ScopeId",
        "ModuleId",
        "uint8_t",
        "uint16_t",
        "uint32_t",
        "uint64_t",
        "int8_t",
        "int16_t",
        "int32_t",
        "int64_t",
        "size_t",
        "char",
        "bool",
    }
    for field in rules.data_fields:
        if "DynArray" in field.cpp_type:
            initializer = ""
        elif field.name == "target" and _short_cpp_type(field.cpp_type) == "SymId":
            initializer = " = kInvalidSymId"
        elif _short_cpp_type(field.cpp_type) in scalar_types:
            initializer = " = 0"
        else:
            initializer = " = {}"
        out.append(f"    {field.cpp_type} {field.name}{initializer};")
    out.append("};")
    out.append("")

    out.append("// symKindName is a thin switch over SymKind.  Defined inline.")
    out.append("inline const char *symKindName(SymKind kind) noexcept {")
    out.append("    switch (kind) {")
    for kind in rules.kinds:
        out.append(f"    case SymKind::{kind}: return {cpp_string(kind)};")
    out.append("    }")
    out.append('    return "?";')
    out.append("}")
    fields = {field.name for field in rules.data_fields}
    required_for_make = {"name", "kind", "visibility"}
    if required_for_make <= fields:
        out.append("")
        out.append("inline const char *visibilityKindName(SymbolVisibilityKind kind) noexcept {")
        out.append("    switch (kind) {")
        out.append("    case SymbolVisibilityKind::Public: return \"Public\";")
        out.append("    case SymbolVisibilityKind::Private: return \"Private\";")
        out.append("    case SymbolVisibilityKind::Module: return \"Module\";")
        out.append("    }")
        out.append('    return "?";')
        out.append("}")
        out.append("")
        out.append("inline const char *visibilityName(const SymbolVisibility &visibility) noexcept {")
        out.append("    return visibilityKindName(visibility.kind);")
        out.append("}")
        out.append("")
        out.append("inline SymbolData makeSymbol(Arena &arena, InternedId name, SymKind kind,")
        out.append("                            SymbolVisibility visibility = SymbolVisibility{}) {")
        has_members = any(field.name == "members" for field in rules.data_fields)
        if has_members:
            out.append("    DynArray<SymId> members{arena};")
        member_expr = "std::move(members)" if has_members else ""
        out.append(("    return SymbolData{0, 0, visibility, 0, kind, 0, Span{}, Span{},"
                    f" kInvalidSymId{', ' if member_expr else ''}{member_expr}}};"))
        out.append("}")

    out.append("} // namespace toolkit::symbols")
    return "\n".join(out) + "\n"


def _emit_source(rules: SymbolsRules) -> str:
    return "// symbols: header-only (no .cpp needed)\n"

def _emit_gitignore() -> str:
    return gitignore_lines(["symbols.hpp"])


def write_generated(out_dir: Path, rules: SymbolsRules) -> list[Path]:
    return write_generated_files(
        out_dir,
        [
            ("symbols.hpp", _emit_header(rules)),
            (".gitignore", _emit_gitignore()),
        ],
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rules", nargs="?", default="src/symbols/symbols.rules")
    parser.add_argument("--out", default="build/src/symbols", help="diretorio de saida")
    args = parser.parse_args()

    rules_path = Path(args.rules)
    out_path = Path(args.out)
    if not rules_path.exists():
        print(f"rules file not found: {rules_path}", file=sys.stderr)
        return 2

    try:
        rules = parse_rules(rules_path.read_text(encoding="utf-8"), rules_path)
    except RuleError as exc:
        print(exc.render(rules_path), file=sys.stderr)
        return 2

    out_path.mkdir(parents=True, exist_ok=True)
    write_generated(out_path, rules)
    if not out_path.name.startswith("."):
        print(f"generated {out_path / 'symbols.hpp'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
